CREATE TABLE IF NOT EXISTS OA_POINTS (
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         BIGINT,
    EVENT_TYPE      VARCHAR(1024),
    EXT_ID          BIGINT,
    TS              BIGINT,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    POINT_ID        VARCHAR(1024),
    SUB_POINT_ID    VARCHAR(1024),
    POINTS          FLOAT(4),
    TAG             VARCHAR(1024),
    IS_ACTIVE       BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS OA_BADGES (
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         BIGINT,
    EVENT_TYPE      VARCHAR(1024),
    EXT_ID          BIGINT,
    TS              BIGINT,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    BADGE_ID        VARCHAR(1024),
    SUB_BADGE_ID    VARCHAR(1024),
    START_EXT_ID    BIGINT,
    END_EXT_ID      BIGINT,
    START_TIME      BIGINT,
    END_TIME        BIGINT,
    TAG             VARCHAR(1024),
    IS_ACTIVE       BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS OA_MILESTONES (
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         BIGINT,
    EVENT_TYPE      VARCHAR(1024),
    EXT_ID          BIGINT,
    TS              BIGINT,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    MILESTONE_ID    VARCHAR(1024),
    LEVEL           INT,
    IS_ACTIVE       BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS OA_MILESTONE_STATE (
    USER_ID         BIGINT,
    MILESTONE_ID    VARCHAR(1024),
    CURRENT_VAL     FLOAT(4),
    CURRENT_VAL_I   BIGINT,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OA_DEFINITIONS (
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    KIND            INT,
    NAME            VARCHAR(1024),
    DISPLAY_NAME    VARCHAR(1024),
    CONTENT_DATA    TEXT,
    GAME_ID         BIGINT,
    PARENT_ID       BIGINT,
    IS_ACTIVE       BOOLEAN DEFAULT 1,
    EXPIRATION_AT   BIGINT,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OA_USERS (
    USER_ID         BIGINT,
    NAME            VARCHAR(1024),
    AVATAR_ID       VARCHAR(1024),
    IS_MALE         BOOLEAN,
    IS_ACTIVE       BOOLEAN DEFAULT 1,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OA_TEAMS (
    TEAM_ID         BIGINT,
    TEAM_SCOPE      BIGINT,
    NAME            VARCHAR(128),
    AVATAR_ID       VARCHAR(1024),
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OA_TEAM_USERS (
    TEAM_ID         BIGINT,
    USER_ID         BIGINT,
    SINCE           BIGINT,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP()
);
