version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    logging:
      driver: none

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    logging:
      driver: none

  enginedb:
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - "./.tmpdata/enginedata:/data"
    ports:
      - "6379:6379"

  apicache:
    image: redis:5
    command: [ "redis-server", "--appendonly", "yes", "--port", "6381"]
    volumes:
      - "./.tmpdata/cache:/data"
    ports:
      - "6381:6381"

  events-api:
    image: oasis/events-api
    ports:
      - "8050:8050"
    volumes:
      - "./buildscripts/events-api.yml:/etc/oasis/events-api.yml"
    environment:
      - "WAIT_HOSTS=apicache:6381,kafka:9092"
      - "O_OASIS_CACHE_CONFIGS_CONNECTIONSTRING=redis://apicache:6381"
      - "O_OASIS_EVENTSTREAM_CONFIGS_BROKERURLS=kafka:9092"
      - "O_OASIS_ADMINAPI_BASEURL=http://stats-api:8010/api"
    depends_on:
      - apicache
      - kafka

  stats-api:
    image: oasis/stats-api
    ports:
      - "8010:8010"
    volumes:
      - "./buildscripts/stats-api.yml:/etc/oasis/stats-api.yml"
      - "./buildscripts/stats-api-spring.yml:/etc/oasis/stats-api-spring.yml"
      - "./buildscripts/modules:/etc/oasis/modules"
    environment:
      - "WAIT_HOSTS=apicache:6381,kafka:9092"
      - "O_OASIS_ENGINEDB_URL=redis://enginedb:6379"
      - "O_OASIS_CACHE_URL=redis://apicache:6381"
      - "O_OASIS_EVENTSTREAM_CONFIGS_BROKERURLS=kafka:9092"
    depends_on:
      - apicache
      - kafka

  engine:
    image: oasis/engine
    environment:
      - "WAIT_HOSTS=enginedb:6379,kafka:9092"
      - "O_OASIS_ENGINE_ID=engine_in_docker_compose"
      - "O_OASIS_ENGINEDB_CONFIGS_URL=redis://enginedb:6379"
      - "O_OASIS_EVENTSTREAM_CONFIGS_BROKERURLS=kafka:9092"
    volumes:
      - "./buildscripts/engine.yml:/etc/oasis/engine.yml"
      - "./buildscripts/modules:/etc/oasis/modules"
    depends_on:
      - enginedb
      - kafka

  feeder:
    image: oasis/feeder
    environment:
      - "WAIT_HOSTS=kafka:9092"
      - "O_OASIS_EVENTSTREAM_CONFIGS_BROKERURLS=kafka:9092"
      - "O_OASIS_ADMINAPI_BASEURL=http://stats-api:8010/api"
    volumes:
      - "./buildscripts/feeder.yml:/etc/oasis/feeder.yml"
      - "./buildscripts/modules:/etc/oasis/modules"
    depends_on:
      - kafka
      - engine