FROM openjdk:8-jre-alpine
MAINTAINER Isuru Weerarathna <uisurumadushanka89@gmail.com>

WORKDIR /usr/share/oasis
ENTRYPOINT ["/usr/bin/java", "-classpath", "./*:libs/*", "io.github.isuru.oasis.injector.Injector"]
EXPOSE 5885

# Add dependency library files
ADD injector/target/libs /usr/share/oasis

# Add main executing jar
ADD injector/target/oasis-injector.jar /usr/share/oasis/oasis-injector.jar